### ISSUE TITLE
Error while saving the result

### ISSUE THREAD

**Issue by OHaiYo-lzy** [lyh-18/TCVC-Temporally-Consistent-Video-Colorization#5]
when I finished testing or train, merely empty dirs are found in result directory.
Then I found that the functions
`save_imglist(k, k + len(out_rgb_img), save_subfolder, out_rgb_img, logger, img_paths)`
in testing codes are no longer working..

But still I can see some of the result via   

            plt.imshow(out_rgb_img[0])

            plt.show()

Any roslutions?
Thx!

**Comment by lyh-18** [comment]
Hi, we checked and ran our codes again. It works fine.
Did you specify the ``save_folder`` correctly?

**Comment by OHaiYo-lzy** [comment]
It worked.thank you!



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 15, 2022 11:32 AM
To: ***@***.***&gt;;
Cc: "Tyrion ***@***.******@***.***&gt;;
Subject: Re: [lyh-18/TCVC-Temporally-Consistent-Video-Colorization] Errorwhile saving the result (Issue #5)




 
Hi, we checked and ran our codes again. It works fine.
 Did you specify the save_folder correctly?
